<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use App\Models\Animal;

class AnimalSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $animals = [
            [
                'name' => 'Buddy',
                'species' => 'dog',
                'breed' => 'Golden Retriever Mix',
                'age' => 3,
                'gender' => 'male',
                'size' => 'large',
                'description' => "Buddy is a friendly and energetic Golden Retriever mix who loves to play fetch and go on long walks. He's great with children and other dogs, making him the perfect family companion. Buddy is house-trained and knows basic commands like sit, stay, and come. He would thrive in a home with a yard where he can run and play.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Special needs: None",
                'adoption_status' => 'available',
                'featured' => true,
                'images' => ['animals/dog-looking-at-camera.jpg', 'animals/dog-sitting.jpg'],
            ],
            [
                'name' => 'Luna',
                'species' => 'cat',
                'breed' => 'Domestic Shorthair',
                'age' => 2,
                'gender' => 'female',
                'size' => 'medium',
                'description' => "Luna is a sweet and gentle cat who loves to curl up in sunny spots and purr contentedly. She's very affectionate with her humans and enjoys being petted and brushed. Luna is litter-trained and gets along well with other cats. She would do best in a quiet home where she can be the center of attention.",
                'medical_history' => "• Spayed: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Special needs: None",
                'adoption_status' => 'available',
                'featured' => true,
                'images' => ['animals/a-cute-cat.jpg', 'animals/cat-looking-at-camera.jpg'],
            ],
            [
                'name' => 'Max',
                'species' => 'dog',
                'breed' => 'German Shepherd Mix',
                'age' => 5,
                'gender' => 'male',
                'size' => 'large',
                'description' => "Max is a loyal and intelligent German Shepherd mix who would make an excellent companion for an active family. He's well-trained and responds well to commands. Max loves hiking, running, and playing in the yard. He's protective of his family but friendly with strangers once properly introduced.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Hip dysplasia: Mild, managed with supplements",
                'adoption_status' => 'pending',
                'featured' => false,
                'images' => ['animals/dog-in-the-feild.jpg', 'animals/hunter-dog.jpg'],
            ],
            [
                'name' => 'Whiskers',
                'species' => 'cat',
                'breed' => 'Maine Coon Mix',
                'age' => 4,
                'gender' => 'male',
                'size' => 'large',
                'description' => "Whiskers is a majestic Maine Coon mix with a fluffy coat and a gentle personality. He's very social and loves to follow his humans around the house. Whiskers enjoys playing with feather toys and laser pointers. He's great with children and would do well in a family setting.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Dental cleaning: Completed",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/cat-on-the-sofa.jpg'],
            ],
            [
                'name' => 'Bella',
                'species' => 'dog',
                'breed' => 'Labrador Mix',
                'age' => 1,
                'gender' => 'female',
                'size' => 'medium',
                'description' => "Bella is a young and playful Labrador mix who's full of energy and love. She's still learning basic commands but is very eager to please. Bella loves playing with toys, going for walks, and meeting new people. She would benefit from puppy training classes and an active family.",
                'medical_history' => "• Spayed: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Special needs: None",
                'adoption_status' => 'available',
                'featured' => true,
                'images' => ['animals/3-puppies.jpg', 'animals/6-cute-puppies.jpg'],
            ],
            [
                'name' => 'Shadow',
                'species' => 'cat',
                'breed' => 'Black Domestic Shorthair',
                'age' => 6,
                'gender' => 'male',
                'size' => 'medium',
                'description' => "Shadow is a calm and dignified senior cat who prefers a quiet environment. He's very affectionate once he gets to know you and loves to sit on laps while you read or watch TV. Shadow is independent but enjoys gentle petting and treats. He would do best as an only pet.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Arthritis: Mild, managed with medication",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/cat-looking.jpg'],
            ],
            [
                'name' => 'Rocky',
                'species' => 'dog',
                'breed' => 'Pit Bull Mix',
                'age' => 4,
                'gender' => 'male',
                'size' => 'medium',
                'description' => "Rocky is a sweet and gentle Pit Bull mix who loves nothing more than cuddling with his humans. Despite his tough appearance, he's a big softie who gets along well with children and other dogs. Rocky is house-trained and knows basic commands. He would thrive in a loving home where he can be part of the family.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Skin allergies: Managed with special diet",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/dog-in-the-grass.jpg', 'animals/dog-holding-branch.jpg'],
            ],
            [
                'name' => 'Mittens',
                'species' => 'cat',
                'breed' => 'Calico',
                'age' => 3,
                'gender' => 'female',
                'size' => 'small',
                'description' => "Mittens is a beautiful calico cat with a playful and curious personality. She loves exploring new places and playing with interactive toys. Mittens is very social and enjoys the company of both humans and other cats. She's litter-trained and would make a wonderful addition to any family.",
                'medical_history' => "• Spayed: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Special needs: None",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/cat-on-the-kitchen-table.jpg'],
            ],
            [
                'name' => 'Charlie',
                'species' => 'dog',
                'breed' => 'Beagle Mix',
                'age' => 7,
                'gender' => 'male',
                'size' => 'small',
                'description' => "Charlie is a senior Beagle mix with a gentle and calm demeanor. He's perfect for someone looking for a low-maintenance companion who still enjoys daily walks and playtime. Charlie is great with children and other pets. He's house-trained and well-behaved, making him an ideal family dog.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Vision: Slightly impaired due to age",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/2-dogs.jpg'],
            ],
            [
                'name' => 'Princess',
                'species' => 'cat',
                'breed' => 'Persian Mix',
                'age' => 5,
                'gender' => 'female',
                'size' => 'medium',
                'description' => "Princess is a beautiful Persian mix who lives up to her name with her regal bearing and luxurious coat. She's a calm and gentle cat who enjoys being pampered and groomed. Princess prefers a quiet environment and would do best as an only pet where she can receive all the attention she deserves.",
                'medical_history' => "• Spayed: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Requires regular grooming due to long coat",
                'adoption_status' => 'adopted',
                'featured' => false,
                'images' => ['animals/cat-on-the-tabble.jpg'],
            ],
            [
                'name' => 'Milo and Otis',
                'species' => 'cat',
                'breed' => 'Bonded Pair - Mixed',
                'age' => 2,
                'gender' => 'male',
                'size' => 'small',
                'description' => "Milo and Otis are a bonded pair of brothers who must be adopted together. These two adorable cats are inseparable and provide comfort to each other. They love to play together, groom each other, and sleep curled up side by side. Both are very social and would make wonderful additions to any family willing to take both.",
                'medical_history' => "• Both neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Special needs: Must be adopted together",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/2-cute-mouses.jpg'],
            ],
            [
                'name' => 'Pepper',
                'species' => 'bird',
                'breed' => 'Cockatiel',
                'age' => 3,
                'gender' => 'female',
                'size' => 'small',
                'description' => "Pepper is a beautiful and intelligent cockatiel who loves to whistle and mimic sounds. She's very social and enjoys interacting with people. Pepper knows several tunes and can say a few words. She would do best with someone who has experience with birds and can provide daily interaction and mental stimulation.",
                'medical_history' => "• Health check: Recent, all clear\n• Wing clipping: Optional based on owner preference\n• Diet: High-quality pellets and fresh vegetables\n• Special needs: Requires daily social interaction",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/parrot.jpg'],
            ],
            [
                'name' => 'Bonnie',
                'species' => 'dog',
                'breed' => 'Mixed Breed',
                'age' => 4,
                'gender' => 'female',
                'size' => 'medium',
                'description' => "Bonnie is a calm and gentle dog who came to us with her best friend Clyde. She's house-trained and great with children. Bonnie would love to find a home where she can be with Clyde, as they complement each other perfectly and provide comfort to one another.",
                'medical_history' => "• Spayed: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Special needs: Prefers to be adopted with Clyde",
                'adoption_status' => 'available',
                'featured' => true,
                'images' => ['animals/dog-and-cat.jpg', 'animals/view-cats-dogs-being-friends.jpg'],
            ],
            [
                'name' => 'Clyde',
                'species' => 'dog',
                'breed' => 'Mixed Breed',
                'age' => 4,
                'gender' => 'male',
                'size' => 'medium',
                'description' => "Clyde is a playful and energetic dog who came to us with his best friend Bonnie. He's house-trained and great with children. Clyde would love to find a home where he can be with Bonnie, as they are bonded and provide comfort to each other.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Special needs: Prefers to be adopted with Bonnie",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/hi-five-cats-dogs-being-friends.jpg'],
            ],
            [
                'name' => 'Patches',
                'species' => 'cat',
                'breed' => 'Tabby Mix',
                'age' => 1,
                'gender' => 'female',
                'size' => 'small',
                'description' => "Patches is a young, playful tabby who loves to explore and play with toys. She's very curious about everything around her and has a sweet, gentle personality. Patches gets along well with other cats and would do great in a multi-pet household. She's looking for a family who will appreciate her playful nature.",
                'medical_history' => "• Spayed: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• FIV/FeLV: Negative\n• Special needs: None",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/cat-and-dog-on-sofa.jpg'],
            ],
            [
                'name' => 'Scout',
                'species' => 'dog',
                'breed' => 'Border Collie Mix',
                'age' => 2,
                'gender' => 'male',
                'size' => 'medium',
                'description' => "Scout is an intelligent and active Border Collie mix who needs a job to do! He loves learning new tricks, playing fetch, and going on adventures. Scout would be perfect for an active family who enjoys hiking, running, or other outdoor activities. He's very trainable and eager to please.",
                'medical_history' => "• Neutered: Yes\n• Vaccinations: Up to date\n• Microchipped: Yes\n• Heartworm: Negative\n• Special needs: Needs lots of mental and physical stimulation",
                'adoption_status' => 'available',
                'featured' => false,
                'images' => ['animals/dog-hugging-human.jpg'],
            ],
            [
                'name' => 'The Puppy Pack',
                'species' => 'dog',
                'breed' => 'Mixed Breed Puppies',
                'age' => 0,
                'gender' => 'female',
                'size' => 'small',
                'description' => "These adorable puppies are looking for their forever homes! This litter of 6 puppies (3 males, 3 females) are about 8 weeks old and ready for adoption. They've been socialized with children and other dogs. Each puppy has their own unique personality - some are more playful, others more cuddly. They'll need puppy training and lots of patience as they grow.",
                'medical_history' => "• First vaccinations: Complete\n• Dewormed: Yes\n• Health check: All healthy\n• Spay/neuter: Will be required at appropriate age\n• Special needs: Puppy training and socialization needed",
                'adoption_status' => 'available',
                'featured' => true,
                'images' => ['animals/3-puppies.jpg', 'animals/6-cute-puppies.jpg'],
            ],
        ];

        foreach ($animals as $animalData) {
            Animal::create($animalData);
        }
    }
}